// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_CoreAnimation.Screens.iPad.BasicUIViewAnimation {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("BasicUIViewAnimationScreen")]
	public partial class BasicUIViewAnimationScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnClickMe;
		
		private MonoTouch.UIKit.UIImageView __mt_imgApress;
		
		private MonoTouch.UIKit.UIToolbar __mt_tlbrMain;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnClickMe")]
		private MonoTouch.UIKit.UIButton btnClickMe {
			get {
				this.__mt_btnClickMe = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnClickMe")));
				return this.__mt_btnClickMe;
			}
			set {
				this.__mt_btnClickMe = value;
				this.SetNativeField("btnClickMe", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgApress")]
		private MonoTouch.UIKit.UIImageView imgApress {
			get {
				this.__mt_imgApress = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgApress")));
				return this.__mt_imgApress;
			}
			set {
				this.__mt_imgApress = value;
				this.SetNativeField("imgApress", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tlbrMain")]
		private MonoTouch.UIKit.UIToolbar tlbrMain {
			get {
				this.__mt_tlbrMain = ((MonoTouch.UIKit.UIToolbar)(this.GetNativeField("tlbrMain")));
				return this.__mt_tlbrMain;
			}
			set {
				this.__mt_tlbrMain = value;
				this.SetNativeField("tlbrMain", value);
			}
		}
	}
}
