// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_CoreAnimation.Screens.iPad.LayerAnimation {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ImplicitAnimationScreen")]
	public partial class ImplicitAnimationScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIToolbar __mt_tlbrMain;
		
		private MonoTouch.UIKit.UIButton __mt_btnAnimate;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tlbrMain")]
		private MonoTouch.UIKit.UIToolbar tlbrMain {
			get {
				this.__mt_tlbrMain = ((MonoTouch.UIKit.UIToolbar)(this.GetNativeField("tlbrMain")));
				return this.__mt_tlbrMain;
			}
			set {
				this.__mt_tlbrMain = value;
				this.SetNativeField("tlbrMain", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnAnimate")]
		private MonoTouch.UIKit.UIButton btnAnimate {
			get {
				this.__mt_btnAnimate = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnAnimate")));
				return this.__mt_btnAnimate;
			}
			set {
				this.__mt_btnAnimate = value;
				this.SetNativeField("btnAnimate", value);
			}
		}
	}
}
