// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_HelloWorld_iPhone {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UILabel __mt_lblResult;
		
		private MonoTouch.UIKit.UIButton __mt_btnClickMe;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("actnButtonClick:")]
		partial void actnButtonClick (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblResult")]
		private MonoTouch.UIKit.UILabel lblResult {
			get {
				this.__mt_lblResult = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblResult")));
				return this.__mt_lblResult;
			}
			set {
				this.__mt_lblResult = value;
				this.SetNativeField("lblResult", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnClickMe")]
		private MonoTouch.UIKit.UIButton btnClickMe {
			get {
				this.__mt_btnClickMe = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnClickMe")));
				return this.__mt_btnClickMe;
			}
			set {
				this.__mt_btnClickMe = value;
				this.SetNativeField("btnClickMe", value);
			}
		}
	}
}
