// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_CoreAnimation.Screens.iPad.ViewTransitions {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("TransitionViewController")]
	public partial class TransitionViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnTransition;
		
		private MonoTouch.UIKit.UISegmentedControl __mt_sgmntTransitionType;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnTransition")]
		private MonoTouch.UIKit.UIButton btnTransition {
			get {
				this.__mt_btnTransition = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnTransition")));
				return this.__mt_btnTransition;
			}
			set {
				this.__mt_btnTransition = value;
				this.SetNativeField("btnTransition", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("sgmntTransitionType")]
		private MonoTouch.UIKit.UISegmentedControl sgmntTransitionType {
			get {
				this.__mt_sgmntTransitionType = ((MonoTouch.UIKit.UISegmentedControl)(this.GetNativeField("sgmntTransitionType")));
				return this.__mt_sgmntTransitionType;
			}
			set {
				this.__mt_sgmntTransitionType = value;
				this.SetNativeField("sgmntTransitionType", value);
			}
		}
	}
}
