// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_Keyboards.Screens.iPhone {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("HomeScreen")]
	public partial class HomeScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextField __mt_txtDefault;
		
		private MonoTouch.UIKit.UITextField __mt_txtEmailAddress;
		
		private MonoTouch.UIKit.UITextField __mt_txtNamePhonePad;
		
		private MonoTouch.UIKit.UITextField __mt_txtNumberPad;
		
		private MonoTouch.UIKit.UITextField __mt_txtNumbersAndPunctuation;
		
		private MonoTouch.UIKit.UITextField __mt_txtURL;
		
		private MonoTouch.UIKit.UIScrollView __mt_scrlMain;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtDefault")]
		private MonoTouch.UIKit.UITextField txtDefault {
			get {
				this.__mt_txtDefault = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtDefault")));
				return this.__mt_txtDefault;
			}
			set {
				this.__mt_txtDefault = value;
				this.SetNativeField("txtDefault", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtEmailAddress")]
		private MonoTouch.UIKit.UITextField txtEmailAddress {
			get {
				this.__mt_txtEmailAddress = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtEmailAddress")));
				return this.__mt_txtEmailAddress;
			}
			set {
				this.__mt_txtEmailAddress = value;
				this.SetNativeField("txtEmailAddress", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtNamePhonePad")]
		private MonoTouch.UIKit.UITextField txtNamePhonePad {
			get {
				this.__mt_txtNamePhonePad = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtNamePhonePad")));
				return this.__mt_txtNamePhonePad;
			}
			set {
				this.__mt_txtNamePhonePad = value;
				this.SetNativeField("txtNamePhonePad", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtNumberPad")]
		private MonoTouch.UIKit.UITextField txtNumberPad {
			get {
				this.__mt_txtNumberPad = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtNumberPad")));
				return this.__mt_txtNumberPad;
			}
			set {
				this.__mt_txtNumberPad = value;
				this.SetNativeField("txtNumberPad", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtNumbersAndPunctuation")]
		private MonoTouch.UIKit.UITextField txtNumbersAndPunctuation {
			get {
				this.__mt_txtNumbersAndPunctuation = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtNumbersAndPunctuation")));
				return this.__mt_txtNumbersAndPunctuation;
			}
			set {
				this.__mt_txtNumbersAndPunctuation = value;
				this.SetNativeField("txtNumbersAndPunctuation", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtURL")]
		private MonoTouch.UIKit.UITextField txtURL {
			get {
				this.__mt_txtURL = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtURL")));
				return this.__mt_txtURL;
			}
			set {
				this.__mt_txtURL = value;
				this.SetNativeField("txtURL", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("scrlMain")]
		private MonoTouch.UIKit.UIScrollView scrlMain {
			get {
				this.__mt_scrlMain = ((MonoTouch.UIKit.UIScrollView)(this.GetNativeField("scrlMain")));
				return this.__mt_scrlMain;
			}
			set {
				this.__mt_scrlMain = value;
				this.SetNativeField("scrlMain", value);
			}
		}
	}
}
