// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_HelloWorld_MultipleScreens {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MainScreen")]
	public partial class MainScreen {
		
		private MonoTouch.UIKit.UIButton __mt_btnHelloUniverse;
		
		private MonoTouch.UIKit.UIButton __mt_btnHelloWorld;
		
		private MonoTouch.UIKit.UINavigationController __mt_navMain;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("btnHelloUniverse")]
		private MonoTouch.UIKit.UIButton btnHelloUniverse {
			get {
				this.__mt_btnHelloUniverse = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnHelloUniverse")));
				return this.__mt_btnHelloUniverse;
			}
			set {
				this.__mt_btnHelloUniverse = value;
				this.SetNativeField("btnHelloUniverse", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnHelloWorld")]
		private MonoTouch.UIKit.UIButton btnHelloWorld {
			get {
				this.__mt_btnHelloWorld = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnHelloWorld")));
				return this.__mt_btnHelloWorld;
			}
			set {
				this.__mt_btnHelloWorld = value;
				this.SetNativeField("btnHelloWorld", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("navMain")]
		private MonoTouch.UIKit.UINavigationController navMain {
			get {
				this.__mt_navMain = ((MonoTouch.UIKit.UINavigationController)(this.GetNativeField("navMain")));
				return this.__mt_navMain;
			}
			set {
				this.__mt_navMain = value;
				this.SetNativeField("navMain", value);
			}
		}
	}
}
