// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_AppSettings {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MainViewController_iPhone")]
	public partial class MainViewController_iPhone {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnSaveSettings;
		
		private MonoTouch.UIKit.UILabel __mt_lblCityOfBirth;
		
		private MonoTouch.UIKit.UILabel __mt_lblFavoriteColor;
		
		private MonoTouch.UIKit.UISlider __mt_sldrHowBig;
		
		private MonoTouch.UIKit.UISwitch __mt_swchStaySignedIn;
		
		private MonoTouch.UIKit.UITextField __mt_txtFavoriteBand;
		
		private MonoTouch.UIKit.UITextField __mt_txtPassword;
		
		private MonoTouch.UIKit.UITextField __mt_txtUsername;
		
		private MonoTouch.UIKit.UIScrollView __mt_scrlMain;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnSaveSettings")]
		private MonoTouch.UIKit.UIButton btnSaveSettings {
			get {
				this.__mt_btnSaveSettings = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnSaveSettings")));
				return this.__mt_btnSaveSettings;
			}
			set {
				this.__mt_btnSaveSettings = value;
				this.SetNativeField("btnSaveSettings", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblCityOfBirth")]
		private MonoTouch.UIKit.UILabel lblCityOfBirth {
			get {
				this.__mt_lblCityOfBirth = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblCityOfBirth")));
				return this.__mt_lblCityOfBirth;
			}
			set {
				this.__mt_lblCityOfBirth = value;
				this.SetNativeField("lblCityOfBirth", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblFavoriteColor")]
		private MonoTouch.UIKit.UILabel lblFavoriteColor {
			get {
				this.__mt_lblFavoriteColor = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblFavoriteColor")));
				return this.__mt_lblFavoriteColor;
			}
			set {
				this.__mt_lblFavoriteColor = value;
				this.SetNativeField("lblFavoriteColor", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("sldrHowBig")]
		private MonoTouch.UIKit.UISlider sldrHowBig {
			get {
				this.__mt_sldrHowBig = ((MonoTouch.UIKit.UISlider)(this.GetNativeField("sldrHowBig")));
				return this.__mt_sldrHowBig;
			}
			set {
				this.__mt_sldrHowBig = value;
				this.SetNativeField("sldrHowBig", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("swchStaySignedIn")]
		private MonoTouch.UIKit.UISwitch swchStaySignedIn {
			get {
				this.__mt_swchStaySignedIn = ((MonoTouch.UIKit.UISwitch)(this.GetNativeField("swchStaySignedIn")));
				return this.__mt_swchStaySignedIn;
			}
			set {
				this.__mt_swchStaySignedIn = value;
				this.SetNativeField("swchStaySignedIn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtFavoriteBand")]
		private MonoTouch.UIKit.UITextField txtFavoriteBand {
			get {
				this.__mt_txtFavoriteBand = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtFavoriteBand")));
				return this.__mt_txtFavoriteBand;
			}
			set {
				this.__mt_txtFavoriteBand = value;
				this.SetNativeField("txtFavoriteBand", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtPassword")]
		private MonoTouch.UIKit.UITextField txtPassword {
			get {
				this.__mt_txtPassword = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtPassword")));
				return this.__mt_txtPassword;
			}
			set {
				this.__mt_txtPassword = value;
				this.SetNativeField("txtPassword", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtUsername")]
		private MonoTouch.UIKit.UITextField txtUsername {
			get {
				this.__mt_txtUsername = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtUsername")));
				return this.__mt_txtUsername;
			}
			set {
				this.__mt_txtUsername = value;
				this.SetNativeField("txtUsername", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("scrlMain")]
		private MonoTouch.UIKit.UIScrollView scrlMain {
			get {
				this.__mt_scrlMain = ((MonoTouch.UIKit.UIScrollView)(this.GetNativeField("scrlMain")));
				return this.__mt_scrlMain;
			}
			set {
				this.__mt_scrlMain = value;
				this.SetNativeField("scrlMain", value);
			}
		}
	}
}
